spring:
  datasource:
    url: jdbc:mysql://mysql.tool.net:23306/db?autoReconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: 123456
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        default_catalog: db
        dialect: org.hibernate.dialect.MySQL5Dialect

---
spring:
  profiles: test

server:
  port: 10081

---
spring:
  profiles: dev

server:
  port: 10080

