spring:
  datasource:
    url: jdbc:mysql://mysql.tool.net:23306/db?autoReconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: 123456
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        default_catalog: db
        dialect: org.hibernate.dialect.MySQL5Dialect

scheduled:
  order-task-in-msec: 3600000

---
spring:
  config:
    activate:
      on-profile: test

server:
  port: 10081

mock-server:
  endpoint: http://mock-server.tool.net:9081

binstd-endpoint:
  url: ${mock-server.endpoint}
  key: test

---
spring:
  config:
    activate:
      on-profile: dev

binstd-endpoint:
  url: https://api.binstd.com
  key: 822c629b7815e01f

server:
  port: 10080